#!/usr/bin/env python3
"""Generate Titan Pilot LaunchOS documents idempotently.

Usage:
  python3 scripts/generate_complete_operating_system.py
  python3 scripts/generate_complete_operating_system.py --force
"""
from __future__ import annotations

import argparse
from pathlib import Path

DOCUMENTS = {
    "01-brand/BRAND_BIBLE_COMPLETE.md": "# Titan Pilot Brand Bible\n\nSource-of-truth rules: supervised AI trading; evidence over claims; calm authority; no returns promises; no gambling language.\n\n## Mission\nMake AI-assisted trading decisions provable, governable, and committee-ready.\n\n## Positioning\nTitan Pilot is the system of record for AI trading decisions.\n\n## Personality\nPrecise, restrained, skeptical, transparent, technically credible.\n\n## Voice\nShort declarative sentences. State evidence, scope, and limits. Never use guaranteed, profitable, winning, effortless, autonomous profits, or high-conviction marketing.\n\n## Visual principles\nDark-first, one blue accent, violet only for model testimony, red only for halted/critical. Numbers are tabular. Motion settles and never bounces.\n\n## Signature lines\n- AI reasons. Software decides.\n- Evidence or it did not happen.\n- The default action is nothing.\n- Supervised AI Trading.\n\n## Governance\nEvery public claim needs a source, evidence date, owner, and expiry review.\n",
    "02-story/STORY_ARCHITECTURE.md": "# Story Architecture\n\n## Category story\nTrading desks already use AI, but cannot prove what it told them. Titan Pilot turns those invisible whispers into evidence.\n\n## Founder story\nThe platform was built infrastructure-first: event spine, replay, reconciliation, recovery, verification, then AI. The sequence demonstrates the company philosophy.\n\n## Customer story\nBefore: scattered prompts, screenshots, uncapped spend, no audit trail. After: cited thesis, adversarial review, deterministic score, approval provenance, replay.\n\n## Investor story\nThe wedge is prop desks; the category is supervised AI trading; the asset is the decision ledger and certification process.\n\n## Demo story\nShow one AI fabrication caught, one veto, one replay proof, one approval flow, and one budget reconciliation.\n",
    "03-messaging/MESSAGING_BIBLE_COMPLETE.md": "# Messaging Bible\n\n## One-liner\nTitan Pilot is the system of record for AI trading decisions.\n\n## 30-second pitch\nYour traders already use AI. Titan Pilot records every thesis, citation, objection, score, approval, refusal, and cost as replayable evidence. It does not promise returns; it gives the desk control and proof.\n\n## Buyer messages\n- Head of Trading: govern AI without slowing the desk.\n- Risk Officer: every decision is reviewable and attributable.\n- Compliance: policy becomes an enforced system.\n- Investor: category-defining system of record, not another signals vendor.\n\n## Objection anchors\nNo alpha claim; provider-agnostic; single-tenant; human approval; hard caps; open evidence schema.\n",
    "05-pricing/PRICING_SYSTEM.md": "# Pricing System\n\n## Principles\nPrice per governed desk, never per signal or trade. Model spend is transparent pass-through. No free pilots.\n\n## Offers\n- Design Partner: $2,500/month, 6 months, first five desks only.\n- TITAN Desk: $4,000/month, up to three symbol sets.\n- Enterprise: $120k/year floor; typical $150k-$250k.\n- AI Desk Audit: $7,500 fixed, later $15,000.\n- Prop Platform: $60k/year plus $8/funded trader/month.\n- OEM: $250k/year floor plus royalties.\n\n## Discount policy\nOnly exchange price for referenceability, term, scope reduction, or strategic data rights. Never discount because the buyer doubts value.\n\n## Renewal\nAnnual governance report, evidence retention, prompt/version history, and committee support are renewal anchors.\n",
    "07-sales/SALES_OS_COMPLETE.md": "# Sales Operating System\n\n## ICP gate\nAt least five traders, existing AI usage, and a committee/regulator to answer to. Two of three qualifies for an audit only.\n\n## Pipeline\nNamed account -> artifact outreach -> discovery -> live evidence demo -> paid AI Desk Audit -> committee proposal -> design partner -> annual subscription.\n\n## Discovery\nAsk where AI is used, who approves it, what records exist, who owns API spend, what the DDQ asks, and what incident would create career risk.\n\n## Proof assets\nSoak report, security audit, DR report, caught-fabrication example, veto example, replay proof.\n\n## Exit criteria\nNo unpaid pilot; no returns promise; no retail; no gray broker; no customer unwilling to keep an audit record.\n",
    "08-investors/INVESTOR_DATA_ROOM_COMPLETE.md": "# Investor Data Room\n\n## 01 Company\nIncorporation, cap table, founder profile, organization chart.\n\n## 02 Product\nProduct design, demo script, roadmap, public instance.\n\n## 03 Technology\nArchitecture handbook, ADR index, certifications, security and DR reports.\n\n## 04 Market\nICP, bottom-up market model, competitor map, category thesis.\n\n## 05 Commercial\nPricing, pipeline, audits, design partners, contracts, references.\n\n## 06 Finance\nP&L, runway, ARR/MRR, unit economics, model-spend COGS.\n\n## 07 Legal\nIP assignment, trademarks, privacy, counsel opinions, insurance.\n\n## 08 Evidence\nClaim register, benchmark reports, corrections, research publications.\n\n## Access rules\nWatermarked, staged permissions, no secrets, no private broker identifiers, access log retained.\n",
    "09-demo/DEMO_PLAYBOOKS_COMPLETE.md": "# Demo Playbooks\n\n## 15 minutes\nProblem -> caught fabrication -> veto -> replay -> ask.\n\n## 30 minutes\nAdd Approval Center, budget ledger, security posture, AI Desk Audit offer.\n\n## 60 minutes\nAdd architecture, prompt governance, replay drill, risk controls, buyer-specific workflow, implementation discussion.\n\n## Rules\nUse real sanitized historical decisions. No fake metrics. No performance claims. Always show a refusal before an approval. End with a dated next step and paid audit proposal.\n",
    "16-customers/CUSTOMER_SUCCESS_OS.md": "# Customer Success OS\n\n## Onboarding phases\n1. Qualification and data-boundary review.\n2. Single-tenant deployment.\n3. Shadow instrumentation.\n4. Evidence review workshop.\n5. Governance baseline report.\n6. Copilot readiness review.\n\n## Health score\nData freshness, cycle coverage, validation rate, committee engagement, audit usage, unresolved incidents, renewal risk.\n\n## Cadence\nWeekly during first month, monthly operating review, quarterly governance review, annual certification refresh.\n\n## Success outcome\nCustomer can answer who used AI, what it said, what evidence supported it, who approved it, what it cost, and what happened.\n",
    "20-operations/COMPANY_OPERATIONS_OS.md": "# Company Operations OS\n\n## Weekly rhythm\nMonday metrics, Tuesday product, Wednesday customer, Thursday research, Friday finance/risk review.\n\n## Decision records\nEvery material company decision has context, alternatives, owner, date, evidence, reversibility, and review date.\n\n## Incident management\nClassify operational, security, customer, legal, and reputation incidents. Preserve evidence, communicate facts, publish correction where public claims were affected.\n\n## Vendor control\nInventory owner, purpose, data access, renewal date, cost, fallback, and offboarding procedure.\n",
    "24-hiring/HIRING_OS.md": "# Hiring OS\n\n## First hires\n1. Founding engineer after roughly eight customers.\n2. Deployment/compliance engineer after repeatable audits.\n3. GTM lead after ten logos and documented founder-sales motion.\n\n## Scorecard\nMission, outcomes, competencies, anti-patterns, 30/60/90 evidence.\n\n## Interview rule\nWork samples over trivia. Candidates must critique a real artifact, document tradeoffs, and demonstrate evidence-first reasoning.\n\n## Cultural invariants\nNo hidden bad news, no unsupported claims, no silent safety weakening, no vanity complexity.\n",
    "21-partnerships/PARTNERSHIP_OS.md": "# Partnership OS\n\n## Priority partners\nPrime brokers, execution platforms, market-data vendors, compliance advisers, model providers, allocators.\n\n## Evaluation\nDistribution, credibility, data access, neutrality, implementation burden, margin, brand risk, exclusivity cost.\n\n## Red lines\nNo removable TITAN evidence mark in OEM deals; no returns co-marketing; no customer-data resale; no exclusivity without guaranteed revenue.\n\n## Pilot structure\nNamed scope, public/private evidence rights, technical owner, commercial owner, 90-day exit criteria.\n",
    "19-finance/FINANCE_OS.md": "# Finance OS\n\n## Core metrics\nCash, runway, MRR, ARR, gross margin, services mix, burn multiple, CAC, payback, logo retention, NRR, concentration, AI cost per desk.\n\n## Controls\nDual approval for payments above threshold, monthly close, vendor reconciliation, tax calendar, evidence-backed forecasts.\n\n## Planning cases\nBase: profitable wedge. Downside: regulation delayed five years. Upside: ten design partners convert and OEM begins.\n\n## Fundraising rule\nRaise only for named accelerants: attestation, engineers, compliance GTM, counsel.\n",
    "22-competition/COMPETITION_INTELLIGENCE.md": "# Competition Intelligence\n\n## Competitor classes\nCharting, signal vendors, strategy builders, execution platforms, terminals, AI governance suites, in-house browser workflows.\n\n## Evaluation axes\nDecision provenance, evidence citations, machine validation, adversarial review, deterministic scoring, approval audit, replay, budget control, provider neutrality, broker neutrality.\n\n## Battlecard rule\nConcede what competitors do better. Never claim feature superiority without dated evidence. Our category distinction: they show a market or signal; TITAN shows a decision that can be cross-examined.\n",
    "23-market-research/MARKET_RESEARCH_FRAMEWORK.md": "# Market Research Framework\n\n## Questions\nWho uses AI today, for what decisions, under what policy, with what evidence, and who bears liability?\n\n## Methods\nBuyer interviews, DDQ collection, regulatory document review, workflow observation, willingness-to-pay tests, loss/incident postmortems.\n\n## Sample discipline\nRecord segment, jurisdiction, desk size, role, existing stack, and confidence. Separate observed facts from inference.\n\n## Outputs\nICP updates, objection frequency, category language, pricing evidence, integration requirements, legal risks.\n",
    "25-assets/ASSETS_LIBRARY.md": "# Assets Library\n\n## Approved asset classes\nLogos, diagrams, screenshots, demo fixtures, reports, decks, one-pagers, social crops, video masters, legal-approved claims.\n\n## Metadata\nOwner, source, license, public/private, created date, review date, checksum, canonical path, derivative list.\n\n## Rules\nNever commit secrets or customer-identifying screenshots. Public assets require claim-register references. Archive rather than overwrite released assets.\n",
}

def main() -> None:
    parser = argparse.ArgumentParser()
    parser.add_argument("--force", action="store_true")
    args = parser.parse_args()
    root = Path(__file__).resolve().parents[1]
    for relative, content in DOCUMENTS.items():
        path = root / relative
        path.parent.mkdir(parents=True, exist_ok=True)
        if path.exists() and not args.force:
            print(f"skip {relative}")
            continue
        path.write_text(content, encoding="utf-8")
        print(f"write {relative}")

if __name__ == "__main__":
    main()
